[build]
  command = "pnpm build"
  publish = "client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[build.processing.images]
  compress = true
